services:
  backend:
    build: ./server
    ports:
      - "5001:5001"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://mongo:27017/todolist_db
    depends_on:
      - mongo
  
  frontend:
    build: ./client
    ports:
      - "5173:80"
    depends_on:
      - backend
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: